// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YMS.Data;

#nullable disable

namespace YMS.Migrations.MesDb
{
    [DbContext(typeof(MesDbContext))]
    [Migration("20241128104917_initload")]
    partial class initload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YMS.MESModels.MESCoil", b =>
                {
                    b.Property<string>("CoilID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CoilBarcodeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Diameter")
                        .HasColumnType("real");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("CoilID");

                    b.ToTable("MESCoils");
                });

            modelBuilder.Entity("YMS.MESModels.MESIncomingCoil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoilID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MESIncomingCoils");
                });
#pragma warning restore 612, 618
        }
    }
}
